name: knowledge_graph_add::entity_resolver
class_name: Agent
color: blue
llm_params:
  engine: gpt-5-mini
  temperature: 1
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
- text
- previous_context
system_context_items: []
type: agent
