name: shared::tool_selector
class_name: Agent
color: "blue"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"
  temperature: 1

allowed_tools: "all"  # Tool selection depends on available tools, fetched dynamically
except_tools: []

user_context_items:
  - date_time
  - plan
  - current_step
  - action
  - action_input


system_context_items:
  - tool_descriptions



