name: kg_explorer::delegator
class_name: Delegator
color: "blue"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5"
  temperature: 1
  api_key: "dummy_api_key"

allowed_tools: []
except_tools: []
allowed_nodes: []

user_context_items:
  - date_time


system_context_items: []
