name: rag_extract_chat
class_name: Agent
color: "magenta"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"
  temperature: 1
allowed_tools: []
user_context_items:
  - agent_input
system_context_items: []

