name: shared::writer
class_name: Agent
color: "red"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"
  temperature: 1

allowed_nodes: [exit_node]

system_context_items:
  - resource_user_data
  - resource_assistant_data

user_context_items:
  - date_time
  - writer_task
  - writer_context
  - purpose
  - audience
  - tone
  - length
  - format_constraints

