name: shared::tool_arguments
class_name: ToolArguments
color: "yellow"
llm_params:
  llm_provider: "openai"
  engine: "gpt-4.1"
  temperature: 0.1

user_context_items:
  - date_time
  - selected_tool
  - tool_args
  - action_input

system_context_items: []
