name: proactive_orchestrator
class_name: Agent
color: "purple"
llm_params:
  llm_provider: "gemini"
  engine: "gemini-3-flash-preview"
  temperature: 0.8

system_context_items:
- resource_user_data
- resource_tracked_activities

user_context_items:
- date_time
- entity_summary
- day_of_week
- resource_afk_statistics_output
- time_since
- location_summary
- resource_weather
- recent_chat_messages
- calendar_events
- active_tickets
- recent_accepted_tickets
- recent_tickets
- resource_tracked_activities
- resource_user_routine
- resource_user_health
- resource_daily_context_generator_output

