name: knowledge_graph_add::standardizer
class_name: Agent
color: cyan
llm_params:
  engine: gpt-4.1
  temperature: .1
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
- node_label
- node_semantic_label
- node_type
- node_category
- known_label_aliases
- context_text
system_context_items: []
type: agent

