name: kg_maintenance::edge_merger_data
class_name: Agent
color: red
llm_params:
  engine: gpt-5-mini
  temperature: 1
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
- merge_edge_data_input
system_context_items: []
type: agent


