name: rag::query_agent
class_name: Agent
color: red
llm_params:
  engine: gpt-5-mini
  temperature: 1
allowed_tools: []
except_tools: []
user_context_items:
- date_time
- task
- information
- plan
- accomplishments
- query_list
- checklist

type: agent
llm_provider: openai
append_fields: [query_list]