name: daily_summary::final_answer
class_name: FinalAnswer
color: "green"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5"
  temperature: 1
  api_key: "dummy_api_key"

allowed_tools: []  # No tools needed for this agent
except_tools: []
allowed_nodes: [manager_exit_node]

user_context_items:
  - date_time
  - task
  - information
  - recent_history

rag_fields:
  task: ["chat"]
  information: ["chat"]

system_context_items:
  - task


