name: scraper
class_name: Agent
color: "magenta"
llm_params:
  llm_provider: "openai"
  engine: "gpt-4o-mini"
  temperature: 0.1
allowed_tools: []
user_context_items:
  - agent_input
system_context_items: []

