name: kg_maintenance::create_importance
class_name: Agent
color: blue
llm_params:
  engine: gpt-4o-mini
  temperature: 0.1
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
- node_label
- node_type
- node_aliases
- node_attributes
- neighborhood_data
- current_importance
- edge_count
system_context_items: []
type: agent
