name: web::planner
class_name: Planner
color: "green"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5"
  temperature: 1
  api_key: "dummy_api_key"

allowed_nodes: [shared::writer, shared::mathematician, shared::final_answer]

allowed_tools:
  all

except_tools: [emi_team]

user_context_items:
  - date_time
  - task
  - information
  - recent_history
  - checklist
  - action_count


system_context_items:
  - tool_descriptions
  - allowed_nodes
  - task


