name: web::planner
class_name: Planner
color: "green"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5"
  temperature: 1
  api_key: "dummy_api_key"

allowed_nodes: [shared::writer, shared::mathematician, shared::final_answer_lite]

allowed_tools:
  all

except_tools: [emi_team]

append_fields: [progress_report]

user_context_items:
  - date_time
  - task
  - information
  - orchestrator_global_objective
  - orchestrator_global_guidance
  - orchestrator_job_id
  - orchestrator_job_guidance
  - progress_report
  - recent_history
  - checklist
  - action_count


system_context_items:
  - tool_descriptions
  - allowed_nodes
  - task


