name: exit
class_name: Agent
color: "red"
llm_provider: "openai"
llm_params:
  engine: "gpt-5-mini"
  temperature: 1

allowed_tools: []

user_context_items:
  - date_time
  - task
  - info
  - final_answer_content
  - summary
  - recent_history
  - important_links
  - checklist
  - progress
  - discovered_info
  - plan

system_context_items:
  - date_time
  - task
