name: slack::expert_writer
class_name: Agent
color: red
llm_params:
  llm_provider: openai
  engine: gpt-5-mini
  temperature: 1

user_context_items:
  - date_time
  - information
  - task

structured_output: AgentForm


