name: memory::final_answer
class_name: FinalAnswer
color: "blue"
llm_params:
  llm_provider: "openai"
  engine: "gpt-4.1-nano"
  temperature: 0.3

allowed_tools: []
except_tools: []
allowed_nodes: [manager_exit_node]

user_context_items:
  - task
  - information
  - recent_history

