name: entertainment_manager::scout
class_name: Planner
color: green
llm_params:
  api_key: dummy_api_key
  engine: gpt-5
  llm_provider: openai
  temperature: 1
allowed_tools: [web_manager]
allowed_nodes:
- entertainment_manager::flow_exit_node
user_context_items:
- date_time
- agent_task
- information
- recent_history
- checklist
- achievements
system_context_items:
- tool_descriptions
- allowed_nodes
- task
- resource_user_data
- resource_assistant_data
type: agent
