name: shared::mathematician
class_name: Agent
color: "red"
llm_params:
  llm_provider: "openai"
  engine: "gpt-4o-mini"
  temperature: 0.1

allowed_nodes: [exit_node]

user_context_items:
  - date_time
  - mathematician_task
  - mathematician_context

rag_fields:
  task: ["chat"]
  information: ["chat"]