name: taxonomy_lookup::taxonomy_lookup_agent
class_name: Agent
llm_params:
  engine: gpt-5
  temperature: 1
  llm_provider: "openai"
description: "Finds the most relevant taxonomy paths based on a description"

user_context_items:
  - top_level_taxonomy
  - description
  - all_paths
  - total_paths
color: cyan
allowed_tools: []
except_tools: []
system_context_items: []
structured_output: true
