name: email_parser
class_name: Agent
color: "red"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"
  temperature: 1

system_context_items: []

user_context_items:
  - date_time
  - agent_input
