name: kg_query::find_nodes
class_name: Planner
color: "blue"
llm_params:
  llm_provider: "openai"
  engine: "gpt-4.1"
  temperature: .1
  api_key: "dummy_api_key"

allowed_tools: [taxonomy_path_finder]
allowed_nodes: [flow_exit_node]

user_context_items:
  - date_time
  - agent_task
  - information
  - recent_history
  - checklist
  - action_count


system_context_items:
  - tool_descriptions
  - allowed_nodes
