name: kg_query::planner
class_name: Planner
color: "green"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5"
  temperature: 1
  api_key: "dummy_api_key"

allowed_tools: [kg_find_edges, kg_describe_node, kg_describe_edge, ask_user, kg_update_node, kg_create_node, kg_create_edge, kg_delete_node, kg_delete_edge]
allowed_nodes: [kg_query::find_nodes, flow_exit_node]

user_context_items:
  - date_time
  - task
  - information
  - recent_history
  - checklist
  - action_count

system_context_items:
  - tool_descriptions
  - allowed_nodes
  - task
  - resource_user_data
  - resource_assistant_data



