name: slack::casual_chat_writer
class_name: Agent
color: red
llm_params:
  llm_provider: openai
  engine: gpt-5-mini
  temperature: 1
user_context_items:
  - date_time
  - information
  - task
  - entity_summary
type: agent
structured_output: AgentForm

