name: knowledge_graph_add::taxonomy_concept_extractor
class_name: Agent
color: cyan
llm_params:
  engine: gpt-4o-mini
  temperature: 0.1
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
- node_label
- node_sentence
- node_type
system_context_items: []
type: agent

