name: emi_team_selector::delegator
class_name: EmiTeamSelectorDelegator
color: "blue"
llm_provider: "openai"
llm_params:
  engine: "gpt-4o-mini"
  temperature: 0.1

# No tools required for Delegator
allowed_tools: []

user_context_items: []


system_context_items: []


