name: kg_maintenance::type_standardizer
class_name: Agent
color: red
llm_params:
  engine: gpt-5-mini
  temperature: 1
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
- text
system_context_items: []
type: agent


