name: knowledge_graph_add::conversation_boundary
class_name: Agent
color: purple
llm_params:
  engine: gpt-5-nano
  temperature: 1
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
- messages
- analysis_window_size
system_context_items: []
type: agent
