name: knowledge_graph_add::node_data_merger
class_name: Agent
color: blue
llm_params:
  engine: gpt-5-mini
  temperature: 1
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
- existing_node_data
- new_node_data
system_context_items: []
type: agent
