name: emi_agent
class_name: EmiAgent
color: "white"
llm_params:
  llm_provider: "gemini"
  engine: "gemini-3-flash-preview"
  temperature: 0.8

system_context_items:
  - resource_header
  - resource_user_data
  - resource_assistant_personality
  - resource_assistant_role
  - resource_core_user_info
  - resource_chat_guidelines

user_context_items:
  - date_time
  - history
  - agent_input

events:
  - emi_chat_request
