name: emi_agent
class_name: EmiAgent
color: "white"
llm_params:
  llm_provider: "openai"
  engine: "gpt-4.1"
  temperature: 0.8

system_context_items:
  - resource_header
  - resource_user_data

user_context_items:
  - date_time
  - entity_summary
  - history
  - agent_input

events:
  - emi_chat_request
