name: notify_user
class_name: NotifyUser
color: "white"
llm_params:
  llm_provider: "openai"
  engine: "gpt-4o-mini"
  temperature: 0.1

user_context_items:
  - date_time
  - notify_info

events:
  - notify_user_request
