name: notify_user
class_name: NotifyUser
color: "white"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"
  temperature: 1

user_context_items:
  - date_time
  - notify_info

system_context_items:
  - resource_user_data.first_name

events:
  - notify_user_request
