name: kg_maintenance::duplicate_detector_random_sampling
class_name: Agent
color: orange
llm_params:
  engine: gpt-5-nano
  temperature: 1
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
- node_list
system_context_items: []
type: agent
