name: rag::planner
class_name: Agent
color: red
llm_params:
  llm_provider: "openai"
  engine: "gpt-4o-mini"
  temperature: 0.1
allowed_tools: []
except_tools: []
allowed_nodes: ["shared::final_answer"]
user_context_items:
- date_time
- task
- information
- checklist
- accomplishments
- query_list
- plan
system_context_items:
- allowed_nodes
rag_fields:
  task: ["chat"]
  information: ["chat"]
type: agent

