name: emi_team_selector::tool_selector
class_name: Agent
color: "blue"
llm_params:
  llm_provider: "openai"
  engine: "gpt-4.1"
  temperature: 0.1

allowed_tools: "all"
except_tools: []

user_context_items:
  - task
  - information

system_context_items:
  - tool_descriptions
