name: emi_team_selector::tool_selector
class_name: Agent
color: "blue"
llm_params:
  llm_provider: "gemini"
  engine: "gemini-3-flash-preview"
  temperature: 1

allowed_tools: "all"
except_tools: []

user_context_items:
  - task
  - information

system_context_items:
  - tool_descriptions
