name: auto_planner_team::planner
class_name: Planner
color: "green"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5"
  temperature: 1
  api_key: "dummy_api_key"

allowed_tools: all
except_tools: [emi_team]
allowed_nodes: [shared::writer, shared::mathematician, auto_planner_team::final_answer]

user_context_items:
  - date_time
  - task
  - information
  - recent_history
  - checklist
  - action_count
  - entity_summary
  - entity_metadata

system_context_items:
  - tool_descriptions
  - allowed_nodes
  - task
  - resource_user_data
  - resource_assistant_data
  - resource_auto_planner_instructions



