name: new_agent
class_name: Agent
color: "red"
llm_provider: "openai"
llm_params:
  engine: "gpt-4o-mini"
  temperature: 0.1

allowed_tools: []
except_tools: []

user_context_items: []

system_context_items: []

