name: rag::checklist
class_name: Agent
color: red
llm_params:
  engine: gpt-4o-mini
  temperature: 0.1
allowed_tools: []
except_tools: []
user_context_items:
- date_time
- task
- information
- plan
- query
- query_list
- checklist
- accomplishments
rag_fields:
  task: ["chat"]
  information: ["chat"]
  query: ["chat"]
type: agent
llm_provider: openai
append_fields: accomplishments # not appending something is up