name: mcp_playwright_interactive_test::planner
class_name: Planner
color: "green"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"


allowed_tools: "all"
except_tools: []

user_context_items:
  - date_time
  - task
  - information
  - recent_history
  - action_count
  - manager_loop_number
  - critic_diagnosis
  - critic_actionable_change
  - critic_confidence

system_context_items:
  - tool_descriptions

