name: taxonomy_team::planner
class_name: Planner
color: "green"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5"
  temperature: 1
  api_key: "dummy_api_key"

allowed_tools: [taxonomy_merge_categories, taxonomy_rename_category, taxonomy_move_category, taxonomy_update_description, taxonomy_create_category]
allowed_nodes: [flow_exit_node]

user_context_items:
  - date_time
  - task
  - information
  - recent_history
  - checklist
  - action_count

system_context_items:
  - tool_descriptions
  - allowed_nodes
  - task



