name: knowledge_graph_add::meta_data_add
class_name: Agent
color: red
llm_params:
  engine: gpt-5
  temperature: 1
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
- nodes
- message_timestamp
- resolved_sentence
system_context_items: []
type: agent


