name: kg_maintenance::description_creator
class_name: Agent
color: red
llm_params:
  engine: gpt-5
  temperature: 1
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
- node_label
- node_type
- node_aliases
- node_attributes
- neighborhood_data
- prior_description
system_context_items: []
type: agent


