name: knowledge_graph_add::edge_merger
agent_class: "Agent"
class_name: Agent
color: blue
llm_params:
  engine: gpt-5-mini
  temperature: 1
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
  - new_edge_data
  - existing_edge_candidates
system_context_items: []
type: agent
