name: ask_user
class_name: AskUser
color: "white"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"
  temperature: 1

system_context_items:
  - resource_user_data

user_context_items:
  - date_time
  - question

events:
  - ask_user_request
