name: daily_summary::calendar_analyzer
class_name: Agent
color: "purple"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5"
  temperature: 1
  api_key: "dummy_api_key"

allowed_tools:
  - get_calendar_events
except_tools: []
allowed_nodes: [flow_exit_node]

user_context_items:
  - date_time
  - recent_history
  - entity_summary

system_context_items:
  - tool_descriptions



