name: kg_maintenance::edge_merger
class_name: Agent
color: red
llm_params:
  engine: gpt-4o-mini
  temperature: 0.1
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
- merge_candidates
system_context_items: []
type: agent


