name: emi_team_selector::tool_arguments
class_name: ToolArguments
color: "yellow"
llm_params:
  llm_provider: "openai"
  engine: "gpt-4o-mini"
  temperature: 0.1

allowed_tools: "all"  # This agent does not use tools itself, it generates tool arguments
except_tools: []

user_context_items:
  - date_time
  - task
  - information
  - selected_tool

system_context_items: []

rag_fields:
  task: ["chat"]
  information: ["chat"]
