name: emi_team_selector::tool_arguments
class_name: ToolArguments
color: "yellow"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"
  temperature: 1

allowed_tools: "all"  # This agent does not use tools itself, it generates tool arguments
except_tools: []

user_context_items:
  - date_time
  - task
  - information
  - pending_tool_name

system_context_items: []
