name: entertainment_manager::planner
class_name: Agent
color: magenta
llm_params:
  engine: gpt-5
  llm_provider: openai
  temperature: 1
allowed_tools: []
user_context_items:
- topic
system_context_items:
  - resource_assistant_data
  - resource_user_data
  - tool_descriptions
type: agent
