name: emi_audio_agent
class_name: EmiAudioAgent
color: "white"
llm_params:
  llm_provider: "openai"
  engine: "gpt-5-mini"
  temperature: 1

system_context_items:
  - resource_header
  - resource_assistant_personality
  - resource_assistant_role
  - resource_core_user_info
  - resource_chat_guidelines
  - resource_user_data

user_context_items:
  - date_time
  - history
  - agent_input

events:
  - emi_chat_speaking_mode_request
