name: playwright::delegator
class_name: PlaywrightCriticDelegator
color: "green"
llm_params: {}

user_context_items:
  - last_agent
  - pending_tool_name
  - next_agent
  - pipeline_stage
  - result

system_context_items: []

