agents:
  - class: Agent
    name: rag::planner
  - class: FinalAnswer
    name: shared::final_answer
  - class: Agent
    name: rag::checklist
  - class: Delegator
    name: shared::delegator
  - class: Agent
    name: rag::query_agent

control_nodes:
  - class: ExitNode
    name: exit_node
  - name: graceful_exit_control_node
    class: GracefulExitControlNode

description: A template for creating a multi agent manager that controls team of agents.
flow_config:
  state_map:
    shared::delegator: rag::planner
    rag::planner: rag::query_agent
    rag::query_agent: rag::checklist
    rag::checklist: rag::planner
    shared::final_answer: exit_node
    graceful_exit: graceful_exit_control_node
    graceful_exit_control_node: shared::final_answer

max_cycles: 50
name: rag_manager
class_name: MultiAgentManager
tools:
  allowed_tools: []
  except_tools: []

role_bindings:
  delegator: shared::delegator
  tool_selector: shared::tool_selector