name: kg_repair_pipeline::analyzer
class_name: Agent
color: blue
llm_params:
  engine: gpt-4.1
  temperature: 0.1
  llm_provider: "openai"
allowed_tools: []
except_tools: []
user_context_items:
- node_label
- node_semantic_label
- node_description
- node_type
- node_category
- node_aliases
- start_date
- start_date_confidence
- end_date
- end_date_confidence
- valid_during
- edge_count
- sample_connections
system_context_items: []
type: agent